version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: logisched_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: o6Qiar6UAUB7
      POSTGRES_DB: agendamento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - automation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agendamento_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: logisched_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:o6Qiar6UAUB7@db:5432/agendamento_db
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: o6Qiar6UAUB7
      POSTGRES_DB: agendamento_db
      ALLOWED_HOSTS: "localhost,127.0.0.1,agenda.logtudo.com.br,www.agenda.logtudo.com.br"

volumes:
  postgres_data:
